import { type NextPage } from "next";
import { useRouter } from 'next/router';
import { useEffect,useState } from "react";
import Head from "next/head";
import Image from 'next/image';

import Footer from "@/layout/Footer.component";
import MainHeader from "@/layout/Header.component";

import toast, { Toaster } from 'react-hot-toast';

import {ftHeroBGImg, ssStreetPrevImg} from "~/assets/images/media";
import ReactPlayer from 'react-player'


const notifyPageMissing = () => toast('This page is coming soon!');
const notifyFuncMissing = () => toast('This functionaility is coming soon!');

const Features: NextPage = () => {
  const HeaderLinks = [ 'Privacy Policy', /*'How to Contribute' /*'Home', 'Features', 'About', 'Support', 'People', 'News & Features'*/];
  const [initialRenderComplete, setInitialRenderComplete] = useState(false);
  const router = useRouter();

  const redirectToLink = () => {
    router.push('https://www.youtube.com/embed/et6FlZXfBvM');
  };

  useEffect(() => {
   setInitialRenderComplete(true);
  }, []);

  return (
    <>
      <Head>
          <title>Soundscape for Everyone</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/Soundscape_Logo.svg" />
      </Head>
      {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
      <main className="flex min-h-screen w-full flex-col bg-grey-bg mt-header-gap font-poppins overflow-x-hidden">
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <MainHeader headerLinks={HeaderLinks} notifyPageMissing = {notifyPageMissing}/>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className='h-phone w-full'>
          <Image
            className="h-full object-cover
                      tv:object-hero-big-screen desktop:object-hero-big-screen
                      laptop:object-hero-big-screen s-laptop:object-left-top
                      tablet:object-left-top mobile:object-left-top"
            src={ftHeroBGImg.src}
            height={0}
            width={0}
            alt={ftHeroBGImg.alt}
          />
        </div>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className="flex w-full h-auto bg-white py-28
                        tv:px-20 desktop:px-20 laptop:px-20 s-laptop:px-20 tablet:px-10 mobile:px-10">
          <div className="flex flex-row flex-wrap w-full h-auto">
            <div className="flex flex-col desktop:basis-1/2 laptop:basis-full s-laptop:basis-full tablet-basis:full py-12 gap-6">
              <h2 className="section-title-orange2 w-fit bg-transparent py-2 font-semibold leading-normal text-orange text-features-title">Audio information in 3D - for more independence and mobility</h2>
              <p className="font-work-sans text-navy-blue font-normal text-xl leading-8">
                Soundscape is a general-purpose application and allows you to switch effortlessly between using it in the real world or in the virtual world, to help build a richer awareness of your surroundings and explore your environment.
                <br/><br/>
                Place your phone in your pocket or bag and enjoy a hands-free Soundscape experience as it automatically calls out what is around you with any standard pair of stereo headphones!
              </p>
            </div>
            <div className="desktop:basis-1/2 laptop:basis-full laptop:w-full s-laptop:basis-full s-laptop:w-full tablet:basis-full tablet:w-full desktop:pl-8 mobile:basis-full">
              <div className='player-wrapper laptop:flex laptop:justify-center'>
                { !initialRenderComplete ? <></> : <ReactPlayer url='https://youtu.be/QR_2eF0YjM0' height='100%' width='100%' className='react-player' /> }
              </div>
            </div>
          </div>
        </div>
      {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        
      </main>
    </>
  )
}

export default Features