import { type NextPage } from "next";
import { useEffect,useState } from "react";
import Head from "next/head";
import Image from 'next/image';

import Footer from "@/layout/Footer.component";
import MainHeader from "@/layout/Header.component";

import toast, { Toaster } from 'react-hot-toast';

import {ftHeroBGImg, ssStreetPrevImg, ftFeat1Img, ftFeat2Img, ftFeat3Img, sAudoFtImg, beaconFtImg, locationFtImg, wayFindingFtImg, bgAppFtImg, mapFtImg} from "~/assets/images/media";
import ReactPlayer from 'react-player'


const notifyPageMissing = () => toast('This page is coming soon!');
const notifyFuncMissing = () => toast('This functionaility is coming soon!');

const Features: NextPage = () => {
  const HeaderLinks = [ 'Privacy Policy', /*'How to Contribute' /*'Home', 'Features', 'About', 'Support', 'People', 'News & Features'*/];
  const [initialRenderComplete, setInitialRenderComplete] = useState(false);

  function redirectToLink(){
    window.open( "https://www.youtube.com/embed/et6FlZXfBvM",'_blank')
  }

  useEffect(() => {
   setInitialRenderComplete(true);
  }, []);

  return (
    <>
      <Head>
          <title>Soundscape for Everyone</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/Soundscape_Logo.svg" />
      </Head>
      {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
      <main className="flex min-h-screen w-full flex-col bg-grey-bg mt-header-gap font-poppins overflow-x-hidden">
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <MainHeader headerLinks={HeaderLinks} notifyPageMissing = {notifyPageMissing}/>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className='h-phone w-full'>
          <Image
            className="h-full object-cover
                      tv:object-hero-big-screen desktop:object-hero-big-screen
                      laptop:object-hero-big-screen s-laptop:object-left-top
                      tablet:object-left-top mobile:object-left-top"
            src={ftHeroBGImg.src}
            height={0}
            width={0}
            alt={ftHeroBGImg.alt}
          />
        </div>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className="flex w-full h-auto bg-white py-28
                        tv:px-20 desktop:px-20 laptop:px-20 s-laptop:px-20 tablet:px-10 mobile:px-10">
          <div className="flex flex-row flex-wrap w-full h-auto">
            <div className="flex flex-col desktop:basis-1/2 laptop:basis-full s-laptop:basis-full tablet-basis:full py-12 gap-6">
              <h2 className="section-title-orange2 w-fit bg-transparent py-2 font-semibold leading-normal text-orange text-features-title">Audio information in 3D - for more independence and mobility</h2>
              <p className="font-work-sans text-dark-grey text-xl leading-8">
                Soundscape is a general-purpose application and allows you to switch effortlessly between using it in the real world or in the virtual world, to help build a richer awareness of your surroundings and explore your environment.
                <br/><br/>
                Place your phone in your pocket or bag and enjoy a hands-free Soundscape experience as it automatically calls out what is around you with any standard pair of stereo headphones!
              </p>
            </div>
            <div className="desktop:basis-1/2 laptop:basis-full laptop:w-full s-laptop:basis-full s-laptop:w-full tablet:basis-full tablet:w-full desktop:pl-8 mobile:basis-full">
              <div className='player-wrapper laptop:flex laptop:justify-center'>
                { !initialRenderComplete ? <></> : <ReactPlayer url='https://youtu.be/QR_2eF0YjM0' height='100%' width='100%' className='react-player' /> }
              </div>
            </div>
          </div>
        </div>
      {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className="flex flex-col w-full h-auto bg-light-grey-bg py-28 
                          tv:px-20 desktop:px-20 laptop:px-20 s-laptop:px-20 tablet:px-10 mobile:px-10">
          <div className="flex flex-row flex-wrap w-full h-auto">
            <div className="flex justify-center desktop:basis-5/12 laptop:basis-full s-laptop:basis-full tablet-basis:full laptop:pb-6 s-laptop:pb-6 tablet:pb-6 mobile:pb-6 pr-10 pt-4">
              <Image className ="h-phone w-fit" src={ssStreetPrevImg.src} alt={ssStreetPrevImg.alt}></Image>
            </div>
            <div className="flex flex-col desktop:basis-7/12 laptop:basis-full s-laptop:basis-full tablet-basis:full desktop:pl-4 py-6 gap-6 pt-8">
                <h2 className="section-title-light-navy-blue w-fit bg-transparent py-2 font-semibold text-light-navy-blue text-3xl ">Soundscape Street Preview</h2>
                <p className="font-work-sans text-navy-blue font-normal text-xl leading-8  mr-16">
                  Soundscape Street Preview breaks fresh ground for Soundscape by providing an innovative tool for virtually exploring the world! With it, you can select any location in the world to preview the area at street level in order to familiarize and build a mental map of the space.
                  <br/><br/>
                  Soundscape Street Preview will help enrich your awareness of familiar places, and help you explore and discover new and unfamiliar places!
                </p>
                <button className="h-auto w-fit bg-navy-blue rounded-primary-btn px-16 py-3 text-white text-laptop font-semibold" onClick={redirectToLink}>Watch the video</button> 
            </div>
          </div>
        </div>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className="flex flex-col w-full h-auto bg-navy-blue py-28 
                         tv:px-20 desktop:px-20 laptop:px-20 s-laptop:px-20 tablet:px-10 mobile:px-10">
          <div className="flex flex-row py-8">
            <div className="desktop:basis-4/12 laptop:basis-full s-laptop:basis-full tablet-basis:full">
              <h2 className="section-title-white w-fit bg-transparent pb-2 pt-4 font-semibold text-white text-3xl leading-10">Explore the world from the comfort of your sofa</h2>
            </div>
          </div>
          <div className="flex flex-row pb-16">
            <div className="desktop:basis-8/12 laptop:basis-full s-laptop:basis-full tablet-basis:full">
              <p className="font-normal text-xl leading-8 text-white">
                When people have more ambient information, they naturally and intuitively create better mental maps, so they can explore more and feel more comfortable and connected in new environments. Soundscape provides spatial information everywhere you go and adds functionality to existing navigation systems.        
              </p>
            </div>
          </div>
          <div className="flex flex-row flex-wrap justify-between w-full h-auto py-5">
            <div className="flex flex-col basis-96 h-auto"> 
              <Image className="w-fill" src={ftFeat1Img.src} alt={ftFeat1Img.alt}/>
              <p className="pt-4 font-medium text-base leading-6 text-dark-gray-blue">Grow your awareness and discover new places.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto"> 
              <Image className="w-fill" src={ftFeat2Img.src} alt={ftFeat2Img.alt} />
              <p className="pt-4 font-medium text-base leading-6 text-dark-gray-blue">Enrich your experience of familiar places and confidently explore the unfamiliar.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto"> 
              <Image className="w-fill" src={ftFeat3Img.src} alt={ftFeat3Img.alt} />
              <p className="pt-4 font-medium text-base leading-6 text-dark-gray-blue">Run it in the background for a rich ambient experience.</p>
            </div>
          </div>
        </div>
        {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
        <div className="flex flex-col w-full h-auto bg-white py-28 
                        tv:px-20 desktop:px-20 laptop:px-20 s-laptop:px-20 tablet:px-10 mobile:px-10">
          <div className="flex flex-row flex-wrap justify-around w-full h-auto">
            <div className="flex flex-col basis-96 h-auto py-10">
              <div className="flex items-center justify-center h-48">
                <Image className="w-36" src={sAudoFtImg.src} alt={sAudoFtImg.alt}/>
              </div>
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >What is spatial audio?</h4>
              <p className="font-work-sans text-dark-grey">Soundscape calls out landmarks in relation to you, letting you connect with your environment naturally and more intuitively without getting in the way of what you’re doing or who you’re with.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto py-10"> 
              <div className="flex justify-center items-center h-48">
                  <Image className="w-max" src={beaconFtImg.src} alt={beaconFtImg.alt}/>
              </div> 
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >Setting a beacon</h4>
              <p className="font-work-sans text-dark-grey">Once you set the audio beacon to a destination, you can put the phone away and walk. Soundscape will call out roads and intersections through your headphones, putting you in control of how you want to get there.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto py-10"> 
              <div className="flex justify-center items-center h-48">
                  <Image className="w-9/12" src={locationFtImg.src} alt={locationFtImg.alt}/>
              </div> 
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >What is spatial audio?</h4>
              <p className="font-work-sans text-dark-grey">My Location, Around Me, and Ahead of Me buttons help build a picture of where you are and what’s around you. “Around Me” will call out four points of interest in a 360-degree sweep, and “Ahead of Me” calls out five items in front of you.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto py-10">
              <div className="flex items-center justify-center h-48">
                <Image className="w-8/12" src={wayFindingFtImg.src} alt={wayFindingFtImg.alt}/>
              </div>
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >Wayfinding</h4>
              <p className="font-work-sans text-dark-grey">Unlike step-by-step instructions, sounds guide you a more natural way to move through spaces and find places on your own terms.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto py-10"> 
              <div className="flex justify-center items-center h-48">
                  <Image className="w-max" src={bgAppFtImg.src} alt={bgAppFtImg.alt}/>
              </div> 
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >Running in the background</h4>
              <p className="font-work-sans text-dark-grey">Soundscape can be used as a stand-alone app, or it can complement other navigational aids by running in the background, helping build a richer ambient awareness of your surroundings.</p>
            </div>
            <div className="flex flex-col basis-96 h-auto py-10"> 
              <div className="flex justify-center items-center h-48">
                  <Image className="w-5/12" src={mapFtImg.src} alt={mapFtImg.alt}/>
              </div> 
              <h4 className="w-fit bg-transparent py-6 font-semibold text-orange text-xl" >OpenStreetMap</h4>
              <p className="font-work-sans text-dark-grey">Soundscape uses <a href="https://www.openstreetmap.org/#map=5/38.007/-95.844"><span className="underline">OpenStreetMap</span></a> data, which is a rich and constantly enhanced community-generated mapping platform.</p>
            </div>
          </div>
        </div>
      {/* ------------------------------------------------------------------------------------------------------------------------------------------------ */}
      <Footer headerLinks={HeaderLinks} notifyPageMissing={notifyPageMissing}/>
      </main>
    </>
  )
}

export default Features